### ISSUE TITLE
Create dev branch

### ISSUE THREAD

**Issue by AdamCroply** [iota-community/iota-wiki#11]
Setup a dev branch for main pull requests and testing.

**Comment by Phyloiota** [comment]
Yes please anyone do this. Keeping Main untouched then for now i think is the way to go. So who can do that? Jerome, Dr. Electron?

**Comment by jlvandenhout** [comment]
I would like to, but I'm not allowed to change the default branch. @Dr-Electron should be able to do this.

**Comment by Phyloiota** [comment]
Lol yeah saw this - develop branch is created now, Dr. Electron can make it default then...

**Comment by Dr-Electron** [comment]
Done
