### ISSUE TITLE
Start enforcing a coding standard

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#221]
I want to start using a formatter and a linter to enforce a code standard so we have a more unified codebase and it is easier for others to contribute. I'm thinking of [Prettier](https://prettier.io/) for code formatting, as it supports all the languages we use in this project out of the box, and [ESLint](https://eslint.org/) with a [React plugin](https://github.com/yannickcr/eslint-plugin-react) to lint our JavaScript. These tools have good IDE integration as well.

**Comment by jlvandenhout** [comment]
@Critical94 and @Dr-Electron, any considerations or experience with alternative tools?

**Comment by Critical94** [comment]
No, never used alternative tools. Prettier and eslint are the most used tools in this area. In the Prettier [installation guide](https://prettier.io/docs/en/install#eslint-and-other-linters), they even explain how to make them play nice with each other.
