### ISSUE TITLE
Active State not working correctly 

### ISSUE THREAD

**Issue by huhn511** [iota-community/iota-wiki#30]
**Describe the bug**
This is the normal Menu, without an active state: 
![Bildschirmfoto 2021-05-27 um 13 43 44](https://user-images.githubusercontent.com/10562055/119820254-8f916b80-bef1-11eb-8906-3f2cd141ba4a.png)

If i click on a page, there should be just one menuitem selected with primary color, this is how it looks now: 
![Bildschirmfoto 2021-05-27 um 13 43 42](https://user-images.githubusercontent.com/10562055/119820278-961fe300-bef1-11eb-9214-f29c0a6a31e3.png)

**Expected behavior**
Just the current menu item should have an active tag.

**Comment by jlvandenhout** [comment]
It seems doc items are activated if they are referenced in the same side bar, regardless of the active path. Changing the items to links fixes this issue.
