### ISSUE TITLE
Add support for Mathjax

### ISSUE THREAD

**Issue by navin1976** [iota-community/iota-wiki#34]
**Is your feature request related to a problem? Please describe.**
In order to describe mathematical problems (especially in reserach posts and specifications), the wiki needs support for math notation.

**Describe the solution you'd like**
Mathjax

**Describe alternatives you've considered**
Briefly described in the linked issue from Docusaurus

**Additional context**
There has been previous discussion about this topic at Docusaurus with a few solutions assessed and a working solution seemingly identified:
https://github.com/facebook/docusaurus/issues/2078

**Comment by Dr-Electron** [comment]
Basically done with 02234131eaea97b11f37cb2f4b30aaeb6d91da82
