### ISSUE TITLE
Blueprints - Navigation Menu Should be collapsable

### ISSUE THREAD

**Issue by huhn511** [iota-community/iota-wiki#440]
**Describe the bug**
There is a navigation bug in Blueprints - the navigation changes after i click on it and there is no way to get back.

**To Reproduce**

1. Go to https://wiki.iota.org/build/welcome
2. Click on 'Blueprints'

**Expected behavior**
 The blueprint navigation menu should be collapsable and don't create new navigation entires

**Screenshots**

https://wiki.iota.org/build/welcome - blueprints is an topic of the build section
![Bildschirmfoto 2022-01-17 um 14 15 55](https://user-images.githubusercontent.com/10562055/149775830-238f7f73-84f6-4342-a691-c49c3fec310f.png)

https://wiki.iota.org/blueprints/introduction - navigations entries changes and there is no way to get back.
![Bildschirmfoto 2022-01-17 um 14 16 01](https://user-images.githubusercontent.com/10562055/149775804-5cebd473-6728-4bac-b624-4e5736cce0b8.png)

**Comment by Dr-Electron** [comment]
This is just how docusaurus works. Blueprints are its own docs with its own docs id as part of the wiki.
We could add a icon to this links like it is done with external links, but not sure if that wouldn't be just be more confusing.
So for now we will keep using what docusaurus provides
