### ISSUE TITLE
Chinese IOTA wiki 

### ISSUE THREAD

**Issue by YTC329** [iota-community/iota-wiki#445]
Hi, we have a strong IOTA community in Taiwan (https://t.me/IOTAmoon) and we might be able to help translate IOTA wiki into Chinese. 
Therefore, I would like to know if the team can open a Chinese language section for IOTA-wiki? Thanks

**Comment by jlvandenhout** [comment]
Thank you for being so patient with us. Priorities were with the Shimmer release and the resulting restructure and versioning implementation. We know you have put in quite some work already to translate the previous version of the Wiki into Chinese, but the current setup of working with repository clones will result in unmanageable workflows. To do this properly we want to start using Crowdin to manage translations, so I'm closing this in favor if #703
