### ISSUE TITLE
Project deployment

### ISSUE THREAD

**Issue by Coder-itCheng** [iota-community/iota-wiki#544]
Hi author, I would like to ask how to deploy this to Netlify or Vercel, I tried to deploy, but found errors in both.The following figure:
![image](https://user-images.githubusercontent.com/67517385/168342834-9623f1b8-05a5-4750-8d2b-07b0ae0ee32e.png)
![image](https://user-images.githubusercontent.com/67517385/168342911-42f9a510-bb23-455c-9f6e-e1aa737e7fd9.png)

**Comment by Dr-Electron** [comment]
Hi, this is a question for the docusaurus team. But I guess as you are trying to deploy our wiki to your own url, Vercel or Netlify may have a problem with that. But as I said not something we can help you with as we don't use Vercel or Netlify
