### ISSUE TITLE
Page crashes 

### ISSUE THREAD

**Issue by Thoralf-M** [iota-community/iota-wiki#557]
https://versioning.iota-community.org/wallet.rs/develop/libraries/rust/examples  Google Chrome in Android
![Screenshot_20220527-153629_Chrome.jpg](https://user-images.githubusercontent.com/46689931/170710967-cd0d8d3b-cda9-4278-adbd-45239678a666.jpg)

**Comment by Dr-Electron** [comment]
Fixed with caf5bfc btw
