### ISSUE TITLE
Use cache in workflows to speed up yarn installations

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#579]
**Is your feature request related to a problem? Please describe.**
We could potentially speed up the workflows a bit by caching between workflow runs.

**Describe the solution you'd like**
Use the provided cache functionality: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data

**Comment by Dr-Electron** [comment]
Fixed with https://github.com/iota-community/iota-wiki/commit/76a768738865e09bfbfb91837170d3985fc34c61
