### ISSUE TITLE
Generalize plugin reducer

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#584]
**Is your feature request related to a problem? Please describe.**
The plugin config reducer is duplicated in `build` and `tutorials` currently.

**Describe the solution you'd like**
Generalize the config reducer to be used by configs, with associated environment variables to configure the reducer behavior.

**Comment by Dr-Electron** [comment]
Fixed with https://github.com/iota-community/iota-wiki/commit/f3574ad4605c3440e7f98dbec00fb51a2e2147f9
