### ISSUE TITLE
Add a topics page where content is listed by topic.

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#59]
As discussed a separate page to navigate content by topic would be a great addition. This would also allow to implement "popular topics" in the landing page header more easily as this would just link to the specific topic in the topics page.

The idea is to use the `keywords` of the frontmatter to automatically index topics during build and fill the topic page with cards for each topic, containing links to the content related to that topic.

The popular topics section on the landing page can be implemented as a React component which is configurable from the Docusaurus config file. So initially we can configure the popular topics manually. At a later stage we could look into how to automate this.

**Comment by Phyloiota** [comment]
Very good idea....
Could we maybe assign labels to the pages here in Github to help to sort that until a keyword font matter search is available?
I will take some time to work on how we could structure this page.
But i really like the idea.... gives another option especially for users that dont know yet what to look for...

**Comment by jlvandenhout** [comment]
Closing this for now as Docusaurus now has tags built in.
