### ISSUE TITLE
Update landing page according to new design and content structure

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#596]
To get ready for Stardust release, Shimmer and provide a more coherent Wiki experience, we started to [restructure Wiki content](https://github.com/iota-community/iota-wiki/discussions/480) and decided to [redesign the landing page](https://www.figma.com/file/23wuFs7X6UyM7gfA2VR0hY/Wiki-Landing-Page?node-id=795%3A6579).

TODO:
- [x] Implement new landing page structure.
- [x] Update styling to match design.
- [x] Update links to correct URLs after updated content is merged (list PRs here?).
- [x] Update texts.
- [x] Update icons.

**Comment by Dr-Electron** [comment]
Closed with https://github.com/iota-community/iota-wiki/pull/597
