### ISSUE TITLE
Implement an in-page rich text editor for non-dev contributions.

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#60]
To allow a greater audience to contribute, the idea is to have an in-page editor that does not require any knowledge of markup languages or git, but transparently translates edited content to Markdown and integrates well with our current GitHub workflows.

Ideally the frontend has the rich text editor look and feel like Google Docs or Word. There are a few open questions:

- Do we want to be able to save our progress locally, to continue at a later time?
- Do we want to allow editing multiple files at the same time? A topic might live at different locations in different forms. Topics might be interrelated.
- If so, how do we present these files? Using tabs in the page or utilize browser tabs?
- Do we want contributors to identify themselves, for example to track contributions and to be able to notify them about requests for updates or changes before their changes are accepted?

**Comment by Phyloiota** [comment]
> To allow a greater audience to contribute, the idea is to have an in-page editor that does not require any knowledge of markup languages or git, but transparently translates edited content to Markdown and integrates well with our current GitHub workflows.
> 
> Ideally the frontend has the rich text editor look and feel like Google Docs or Word. There are a few open questions:
> 
> * Do we want to be able to save our progress locally, to continue at a later time?
> * Do we want to allow editing multiple files at the same time? A topic might live at different locations in different forms. Topics might be interrelated.
> * If so, how do we present these files? Using tabs in the page or utilize browser tabs?
> * Do we want contributors to identify themselves, for example to track contributions and to be able to notify them about requests for updates or changes before their changes are accepted?


Firstly - absolutely love how far you have brought this already! Applause!!!
To your questions...
- saving locally would be a cool feature - as content can grow big... but that should be an easy task and not make things harder for you to create the editor. If you say its not super much extra work, okay then go for it...
- editing multiple files.... i think that is not needed atm. maybe leads to confusing? Better have it strict limited to work on one file at a time... only if we would have accounts for users, then we can extend the functionality and then they could have several open issues / files they work on. I would say open those in browser tabs i think thats again easier to implement?
- having a user account option is something we should think about... That would go hand in hand with the hopefully upcoming "IOTA account".... in the moment we could have a login with discord, or even better with Github, so they can get notifications etc from Github... and still use the editor so they dont need to handle md files...
But again thats not super priority atm i think...only if it is an easy implementable task...
I would say - if we dont go for a "wiki account management", users could add minimum their Discord username to identify them?
