### ISSUE TITLE
Fix Stardust page not found

### ISSUE THREAD

**Issue by annie101101046** [iota-community/iota-wiki#615]
**Describe the bug**
When clicked `Networks` and then clicked the left side `Developer` > `Stardust`, it will show a page not found

**To Reproduce**

1. Go to [stardust.iota-community.org](http://stardust.iota-community.org/)
2. Click on 'Network'
3. Click on left-side's  'Developer' > 'Stardust'
4. See [page not found](https://stardust.iota-community.org/networks/introduction/develop/welcome)

**Expected behavior**
Show Stardust page contents

**Screenshots**
<img width="1346" alt="截圖 2022-07-14 下午3 43 18" src="https://user-images.githubusercontent.com/11192870/178929229-bfdbf7d3-fa2e-488c-b76d-b0c088b60c2c.png">

**Desktop (please complete the following information):**
Browser: Chrome version 102.0.5005.115

**Comment by Dr-Electron** [comment]
Solved in https://github.com/iota-community/iota-wiki/commit/28ce8c73d03452f0ba7bd31532bc1b1ebb01592b
