### ISSUE TITLE
[Suggestion] Change the IOTA nodes order in the landing page

### ISSUE THREAD

**Issue by antonionardella** [iota-community/iota-wiki#616]
**Describe the solution you'd like**
From an architectural standpoint, my suggestion is to change the order of the nodes
Baselayer nodes first (Hornet, Bee)
Followed by SmartContract chain validators (Wasp)
Then Chronicle (which will disappear as it is becoming an INX plugin, correct?)

![image](https://user-images.githubusercontent.com/7383572/178930629-10ec38e8-b922-4532-8823-4eb2c98389da.png)

**Comment by Dr-Electron** [comment]
Fixed in cfbbd8fb56645060b7b8ceb7d0b3ec6ce8d161df
