### ISSUE TITLE
Libraries sections shows frameworks

### ISSUE THREAD

**Issue by Thoralf-M** [iota-community/iota-wiki#621]
**Describe the bug**

**To Reproduce**
Click on Libraries section at the top

**Expected behavior**
Should show client and wallet libraries

**Screenshots**
![image](https://user-images.githubusercontent.com/46689931/179200656-acdd6dae-661d-4cf4-a366-3b3b4d1578d5.png)

**Desktop (please complete the following information):**
- Browser [e.g. chrome]

**Comment by Dr-Electron** [comment]
Fixed for now with https://github.com/iota-community/iota-wiki/commit/0510e293b15a84a028b85a9c7fee8634ce1a9cf1

Maybe we should do something like this https://github.com/iota-community/iota-wiki/issues/630 in the future
