### ISSUE TITLE
Fix Contribute URL

### ISSUE THREAD

**Issue by annie101101046** [iota-community/iota-wiki#628]
**Describe the bug**
When scrolling down to the footer and clicking "contribute" it will show a page not found

**To Reproduce**

1. Go to 'https://stardust.iota-community.org/'
2. Scroll down to 'footer'
3. Click 'Contribute'
4. See Page not found error

**Expected behavior**
Linke to URL: https://stardust.iota-community.org/learn/contribute-to-wiki/welcome

**Screenshots**
<img width="1118" alt="截圖 2022-07-18 上午9 33 35" src="https://user-images.githubusercontent.com/11192870/179433866-3ed39960-e8ef-4f27-999c-91b92667847c.png">

**Desktop (please complete the following information):**
Chrome Version 102.0.5005.115

**Comment by Dr-Electron** [comment]
Fixed in 77f90aec478b244bcf4bfd5713529527da7ab00d
