### ISSUE TITLE
Just scroll to libraries if you click on Libraries in the navbar

### ISSUE THREAD

**Issue by Dr-Electron** [iota-community/iota-wiki#630]
Instead of having it's own libraries section we maybe should just link to the landing page? Seems too complicated to me right now 🤔

**Comment by jlvandenhout** [comment]
I had my doubts, but I agree. Duplicating the cards in their own page to link to doesn't add much and at least the cards on the landing page give a better overview and UX than the current Libraries section.

**Comment by jlvandenhout** [comment]
Although it might feel weird to get linked to a subsection of a page that lists more than just libraries versus a single page just listing the libraries so you know where it ends. It might lead to some dissonance, but let's see. I can create two versions and we can compare.

**Comment by jlvandenhout** [comment]
Closed by #658
