### ISSUE TITLE
Create indicator for location

### ISSUE THREAD

**Issue by Dr-Electron** [iota-community/iota-wiki#637]
**Is your feature request related to a problem? Please describe.**

With the old mega menu we had an indicator in the dropdown where you are. May make sense to have something in the new wiki as it may be confusing if you get redirected to a new plugin-docs instance. You may loose track of where you are

**Comment by jlvandenhout** [comment]
Disregard the above, breadcrumbs are local to the doc, so that won't help much in this case.

**Comment by Dr-Electron** [comment]
Fixed in https://github.com/iota-community/iota-wiki/commit/7b26e6f36f22662df97c6ff55b88c5a82679962c
