### ISSUE TITLE
Write Content for: LEARN/Networks/IOTA 1.5 - Chrysalis

### ISSUE THREAD

**Issue by Phyloiota** [iota-community/iota-wiki#64]
LEARN/Networks/IOTA 1.5 - Chrysalis

**Comment by Phyloiota** [comment]
Topic work in Progress by   https://github.com/WilliamDS

**Comment by DanieKrie** [comment]
> Topic work in Progress by https://github.com/WilliamDS

Wrote some content here: https://github.com/iota-community/iota-wiki/pull/63 
Still struggeling with github: don´t know how to assign tasks - sorry :-(

**Comment by Phyloiota** [comment]
Hehe - so now its assigned to you and you should have access to more functions :)

**Comment by DanieKrie** [comment]
> Hehe - so now its assigned to you and you should have access to more functions :)

Nice! Thank you. More functions are not available, so far, but at the moment I actually don´t need them, I guess.
