### ISSUE TITLE
Add tutorials to navbar

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#642]
**Is your feature request related to a problem? Please describe.**
The tutorials are available, but currently not reachable from the navbar.

We should make some room for tutorials, especially on smaller screens.

**Comment by lucas-tortora** [comment]
@jlvandenhout , could we make this developer resources as in the home page instead? We were talking about the integration service docs with @dominic22 and they are also only reachable from the home page.  

If we make it about developer resources we could promote or give focus to other resources the dev ex teams, and other teams, may come up with as well as tutorials.  WDYT?

**Comment by jlvandenhout** [comment]
Good point. I like the idea very much.
