### ISSUE TITLE
Dropdown navbar

### ISSUE THREAD

**Issue by lucas-tortora** [iota-community/iota-wiki#648]
**Is your feature request related to a problem? Please describe.**

Currently, the only ways to access most of the developer documentation are by scrolling to the project on the home page or going into a navbar category and then looking for the project.  

**Describe the solution you'd like**

We could have a menu open when the user's mouse is over the navbar categories. So at any given time, you could, for example, put your mouse over Nodes and reach Hornet or Bee in a single click.

**Comment by jlvandenhout** [comment]
You mean... bring back the mega menu? :trollface: But yes makes total sense.

**Comment by Dr-Electron** [comment]
We can also use the default dropdown here, right? RIGHT? :trollface:

**Comment by jlvandenhout** [comment]
Where's the ban hammer when you need one

**Comment by Dr-Electron** [comment]
🔨
