### ISSUE TITLE
Proposal for the Readme.md

### ISSUE THREAD

**Issue by huhn511** [iota-community/iota-wiki#7]
## General
- Link to Live Wiki Page
- Ask designer for a cool hero image.

## Contributions:
- Link Discord with channel name
- List core maintainers (with GitHub and Discord name) 

## Misc
And a general question for the wiki team - is there a plan to also extend the wikipedia.org pages?
For example:
- https://en.wikipedia.org/wiki/IOTA_(technology) 
- https://en.wikipedia.org/wiki/Tangle

Thanks for doing this! ❤️

**Comment by jlvandenhout** [comment]
With regard to extending to the Wikipedia pages, we discussed this with Antonio and found that it would be better to keep efforts separated. This project will be all about introductory content and to get you to the right documentation, blogs, videos, etc. when you need the details. So the intention is different from the Wikipedia page.
